AllCops:
  TargetRubyVersion: 2.6

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignHash:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/HandleExceptions:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/AbcSize:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/omniauth-suomifi.rb

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact
