language: ruby

rvm:
 - 2.6.3

env:
  global:
    - BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"
    - BUNDLE_PATH="$HOME/.bundle"

script:
  - bundle exec rake test_app
  - SIMPLECOV=1 CODECOV=1 bundle exec rake
